# Input data
resolution: 1024                 

# Training hyperparameters                 
batch_size: 16               
epochs: 20  

# Optimizer parameters               
lr: 0.0001    
beta_1: 0.9                   
beta_2: 0.999
weight_decay: 0.0005  

# Learning rate scheduler                  
step_size: 4                
gamma: 0.1                                 

# Tensorboard log options
image_save_iter: 3000         
image_log_iter: 10000         
log_iter: 10

# Loss weight
corr_threshold: 1
lambda:
  re: 1
  reg: 100
  un: 1
  ort: 1
  id: 0